
    - <<: *api-dev
      awsRegionName: us-east-1
      baseDirectory: v2/infra/terraform/service-teams/ams-test-fahad/boltapi/any-any
      runnerLabel: development
    - <<: *api-dev
      awsRegionName: us-east-1
      baseDirectory: v2/infra/terraform/service-teams/ams-test-six/boltapi/any-any
      runnerLabel: development
    - <<: *api-dev
      awsRegionName: us-east-1
      baseDirectory: v2/infra/terraform/service-teams/test-ams-one/boltapi/any-any
      runnerLabel: development