name: Onboard a new OMD service
description: Onboard a new OMD service
labels: ["onboard_new_service"]
body:
- type: input
  id: omd_service_name
  attributes:
    label: OMD Service Name
  validations:
    required: true
- type: checkboxes
  id: cluster_type
  attributes:
    label: Select Cluster Type(s)
    options:
    - label: boltapi
    - label: bolto11y
  validations:
    required: true
- type: checkboxes
  id: environment
  attributes:
    label: Select Environment(s)
    options:
    - label: dev
    - label: int
    - label: stage
    - label: prod
  validations:
    required: true
- type: input
  id: omd_component_names
  attributes:
    label: OMD Component Name(s) [Comma Separated]
  validations:
    required: true
