name: 'Issue Parser Action'
description: 'Output a JSON representation of data input in a Github Issue'

inputs:
  template-path:
    description: 'Path to the issue form template file'
  issue-body:
    required: true
    description: 'Issue body to parse'
    default: ${{ github.event.issue.body }}

outputs:
  jsonString:
    description: 'JSON string'


runs:
  using: 'node20'
  main: 'dist/index.js'