name: Create New Service Account
run-name: ${{ github.actor }} is creating a new service account
on:
  issues:
    types: [opened]
jobs:
  process-issue:
    if: contains(github.event.issue.labels.*.name, 'onboard_new_service')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create new branch
        run: |
          git checkout -b ${{ github.actor }}-issue-${{ github.run_number }} main

      - name: Parse Issue body
        uses: ./.github/actions/issue-body-parser
        id: issue-parser
        with:
          template-path: ./.github/ISSUE_TEMPLATE/onboard-new-service.yaml # optional but recommended
      
      - name: Output Issue Body 
        run: cat ${HOME}/issue-parser-result.json

      - name: Make File Changes
        run: |
          python3 ./v2/scripts/create_new_service_account.py
          pwd
          ls -lrtha
      
      - name: Commit Changes
        run: | 
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

          pwd
          ls -lrtha v2/infra/terraform/service-teams/ams-test-fahad
          git --version
          git branch

          git checkout 
          git add --all
          git commit -m "${{ github.event.issue.title }}"
          git push -u origin ${{ github.actor }}-issue-${{ github.run_number }}
          gh pr create --base main --title "${{ github.event.issue.title }}" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

