name: Sample Workflow
run-name: ${{ github.actor }} is creating a custom GitHub Actions
on:
  issues:
    types: [opened]
jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Linux Commands
        run: |
         pwd
         ls -lrtha
         echo $HOME
         echo ${{ env.WORK_DIR }}
      - name: Parse Issue Template
        uses: ./.github/actions/issue-body-parser
        id: issue-parser
        with:
          template-path: ./.github/ISSUE_TEMPLATE/onboard-new-service.yaml # optional but recommended
      
      - run: cat ${HOME}/issue-parser-result.json