name: Create New Service Account
run-name: ${{ github.actor }} is creating a new service account
on:
  issues:
    types: [opened]
jobs:
  process-issue:
    if: contains(github.event.issue.labels.*.name, 'onboard_new_service')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse Issue body
        uses: ./.github/actions/issue-body-parser
        id: issue-parser
        with:
          template-path: ./.github/ISSUE_TEMPLATE/onboard-new-service.yaml # optional but recommended
      
      - name: Output Issue Body 
        run: cat ${HOME}/issue-parser-result.json

      - name: Make File Changes
        run: |
          pwd
          ls -lrtha
          python3 ./v2/infra/scripts/create_new_service_account.py
