name: Sample Workflow
run-name: ${{ github.actor }} is creating a custom GitHub Actions
on:
  issues:
    types: [opened]
jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run commands
        run: |
         pwd
         ls -lrth
         echo $HOME
         echo ${{ env.WORK_DIR }}
      - name: Parse Issue Template
        uses: ./
        id: issue-parser
        with:
          template-path: /.github/ISSUE_TEMPLATE/new-omd-service.yaml # optional but recommended
      
      - run: cat ${HOME}/issue-parser-result.json